name: CI-Build-Resume

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted 
    
    steps:
      - name: Checkout Application Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t aadesh2002/resume-app:$IMAGE_TAG ./app
          docker push aadesh2002/resume-app:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Update GitOps Repo with New Tag
        run: |
          git config --global user.email "adesh.v.chaugule@gmail.com"
          git config --global user.name "AadeshChaugule"
          
          git clone https://x-access-token:${{ secrets.GITOPS_REPO_TOKEN }}@github.com/AadeshChaugule/resume-gitops-config.git
          cd resume-gitops-config
          
          sed -i "s/tag: .*/tag: \"${{ env.IMAGE_TAG }}\"/" helm-chart/values.yaml
          
          git add helm-chart/values.yaml
          git commit -m "Update image tag to ${{ env.IMAGE_TAG }} [skip ci]"
          git push origin main
